### PR TITLE
Try parallel

### PR DESCRIPTION
**Pull request by michaelneale**

### CODE REVIEW

**Comment by michaelneale** [comment]
I still can't quite work out how to use volumes to share the target (built artifacts) between step groups (or indeed steps). 

Any ideas? 

maybe @mlocher ?

**Comment by mlocher** [comment]
@michaelneale I'll take a look at that tomorrow (it's getting late over here), and will get back to you once I got a chance to look at the project and the current setup.

**Comment by michaelneale** [comment]
@mlocher I think I may have worked it out - in the sample I coped WORKDIR was /app

however the volumes was ....:/target

removing WORKDIR and the persisted stuff shows up... I still may be missing the point (I am still getting my head around container-per-step)

**Comment by mlocher** [comment]
@michaelneale Yeah, removing the `WORKDIR` would make that work, you could also adapt the volume to get mounted at `/app/target` instead of `/target`

I tried both, the version currently on this branch as well as with the `WORKDIR` enabled and the volume defined as `./tmp:/app/target` and both builds worked. Including the `tmp` directory in the cloned repository root with persisted files)

As for the container per step concept, let me know if you have any specific questions that you'd like me to answer right away, otherwise we can talk about it in our call on Monday.

**Comment by michaelneale** [comment]
thanks @mlocher - I merged pr #3 which uses this, but I tidied it up so that every little step isn't starting up redis etc each time - but same thing as here. I think I get it now!

**Pull request merged**
